name: cardsapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.0.0
  flutter_svg: ^1.0.0
  flutter_slidable: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/kart.png
    - lib/assets/images/wallpaper.png
    - lib/assets/icons/morMenu.svg 
    - lib/assets/icons/griMenu.svg 
    - lib/assets/icons/morMain.svg 
    - lib/assets/icons/griMain.svg 
    - lib/assets/icons/morTarot.svg 
    - lib/assets/icons/griTarot.svg 
    - lib/assets/icons/morGecmis.svg 
    - lib/assets/icons/griGecmis.svg 
    - lib/assets/images/kartlar/adalet.png
    - lib/assets/images/kartlar/araba.png
    - lib/assets/images/kartlar/asiklar.png
    - lib/assets/images/kartlar/asilanAdam.png
    - lib/assets/images/kartlar/ay.png
    - lib/assets/images/kartlar/aziz.png
    - lib/assets/images/kartlar/azize.png
    - lib/assets/images/kartlar/buyucu.png
    - lib/assets/images/kartlar/degnek-altilisi.png
    - lib/assets/images/kartlar/degnek-asi.png
    - lib/assets/images/kartlar/degnek-beslisi.png
    - lib/assets/images/kartlar/degnek-dokuzlusu.png
    - lib/assets/images/kartlar/degnek-dortlusu.png
    - lib/assets/images/kartlar/degnek-ikilisi.png
    - lib/assets/images/kartlar/degnek-krali.png
    - lib/assets/images/kartlar/degnek-kralicesi.png
    - lib/assets/images/kartlar/degnek-onlusu.png
    - lib/assets/images/kartlar/degnek-prensi.png
    - lib/assets/images/kartlar/degnek-sekizlisi.png
    - lib/assets/images/kartlar/degnek-sovalyesi.png
    - lib/assets/images/kartlar/degnek-uclusu.png
    - lib/assets/images/kartlar/degnek-yedilisi.png
    - lib/assets/images/kartlar/denge.png
    - lib/assets/images/kartlar/dunya.png
    - lib/assets/images/kartlar/ermis.png
    - lib/assets/images/kartlar/guc.png
    - lib/assets/images/kartlar/gunes.png
    - lib/assets/images/kartlar/imparator.png
    - lib/assets/images/kartlar/imparatorice.png
    - lib/assets/images/kartlar/joker.png
    - lib/assets/images/kartlar/kader.png
    - lib/assets/images/kartlar/kilic-altilisi.png
    - lib/assets/images/kartlar/kilic-asi.png
    - lib/assets/images/kartlar/kilic-beslisi.png
    - lib/assets/images/kartlar/kilic-dokuzlusu.png
    - lib/assets/images/kartlar/kilic-dortlusu.png
    - lib/assets/images/kartlar/kilic-ikilisi.png
    - lib/assets/images/kartlar/kilic-krali.png
    - lib/assets/images/kartlar/kilic-kralicesi.png
    - lib/assets/images/kartlar/kilic-onlusu.png
    - lib/assets/images/kartlar/kilic-prensi.png
    - lib/assets/images/kartlar/kilic-sekizlisi.png
    - lib/assets/images/kartlar/kilic-sovalyesi.png
    - lib/assets/images/kartlar/kilic-uclusu.png
    - lib/assets/images/kartlar/kilic-yedilisi.png
    - lib/assets/images/kartlar/kule.png
    - lib/assets/images/kartlar/kupa-altilisi.png
    - lib/assets/images/kartlar/kupa-asi.png
    - lib/assets/images/kartlar/kupa-beslisi.png
    - lib/assets/images/kartlar/kupa-dokuzlusu.png
    - lib/assets/images/kartlar/kupa-dortlusu.png
    - lib/assets/images/kartlar/kupa-ikilisi.png
    - lib/assets/images/kartlar/kupa-krali.png
    - lib/assets/images/kartlar/kupa-kralicesi.png
    - lib/assets/images/kartlar/kupa-onlusu.png
    - lib/assets/images/kartlar/kupa-prensi.png
    - lib/assets/images/kartlar/kupa-sekizlisi.png
    - lib/assets/images/kartlar/kupa-sovalyesi.png
    - lib/assets/images/kartlar/kupa-uclusu.png
    - lib/assets/images/kartlar/kupa-yedilisi.png
    - lib/assets/images/kartlar/mahkeme.png
    - lib/assets/images/kartlar/olum.png
    - lib/assets/images/kartlar/seytan.png
    - lib/assets/images/kartlar/tilsim-altilisi.png
    - lib/assets/images/kartlar/tilsim-asi.png
    - lib/assets/images/kartlar/tilsim-beslisi.png
    - lib/assets/images/kartlar/tilsim-dokuzlusu.png
    - lib/assets/images/kartlar/tilsim-dortlusu.png
    - lib/assets/images/kartlar/tilsim-ikilisi.png
    - lib/assets/images/kartlar/tilsim-krali.png
    - lib/assets/images/kartlar/tilsim-kralicesi.png
    - lib/assets/images/kartlar/tilsim-onlusu.png
    - lib/assets/images/kartlar/tilsim-prensi.png
    - lib/assets/images/kartlar/tilsim-sekizlisi.png
    - lib/assets/images/kartlar/tilsim-sovalyesi.png
    - lib/assets/images/kartlar/tilsim-uclusu.png
    - lib/assets/images/kartlar/tilsim-yedilisi.png
    - lib/assets/images/kartlar/yildiz.png

  fonts:
    - family: CinzelDecorative
      fonts:
        - asset: lib/assets/fonts/CinzelDecorative-Bold.ttf   

    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Medium.ttf  

    - family: PlayfairDisplay
      fonts:
        - asset: lib/assets/fonts/PlayfairDisplay-Bold.ttf  

    - family: LibreBaskerville
      fonts:
        - asset: lib/assets/fonts/LibreBaskerville-Regular.ttf  
        
        
 
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
